# Generated by Django 4.2.16 on 2024-11-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('yearOfEntry', models.CharField(db_column='year_of_entry', max_length=4)),
                ('yearProcess', models.CharField(db_column='year_process', max_length=4)),
                ('dateStart', models.DateTimeField(db_column='date_start')),
                ('dateEnd', models.DateTimeField(db_column='date_end')),
                ('importantDates', models.TextField(db_column='important_dates')),
                ('shifts', models.TextField()),
                ('processType', models.CharField(db_column='process_type', max_length=1)),
                ('registerState', models.CharField(db_column='register_state', default='A', max_length=1)),
            ],
            options={
                'db_table': 'processes',
            },
        ),
    ]
