# Generated by Django 4.2.16 on 2024-11-25 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='dateEnd',
            field=models.DateField(db_column='date_end'),
        ),
        migrations.AlterField(
            model_name='process',
            name='dateStart',
            field=models.DateField(db_column='date_start'),
        ),
    ]
