# Generated by Django 4.2.16 on 2024-12-22 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0005_remove_courseteacherrelation_registerstate'),
        ('userAuth', '0001_initial'),
        ('processes', '0003_processusercerprunsarelation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processusercerprunsarelation',
            name='course',
        ),
        migrations.RemoveField(
            model_name='processusercerprunsarelation',
            name='process',
        ),
        migrations.RemoveField(
            model_name='processusercerprunsarelation',
            name='role',
        ),
        migrations.RemoveField(
            model_name='processusercerprunsarelation',
            name='userCeprunsa',
        ),
        migrations.AddField(
            model_name='processusercerprunsarelation',
            name='idCourse',
            field=models.ForeignKey(blank=True, db_column='id_course', null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='processusercerprunsarelation',
            name='idProcess',
            field=models.ForeignKey(db_column='id_process', default=1, on_delete=django.db.models.deletion.CASCADE, to='processes.process'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processusercerprunsarelation',
            name='idRole',
            field=models.ForeignKey(db_column='id_role', default=1, on_delete=django.db.models.deletion.CASCADE, to='userAuth.roleceprunsa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processusercerprunsarelation',
            name='idUserCeprunsa',
            field=models.ForeignKey(db_column='id_user_ceprunsa', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='processusercerprunsarelation',
            name='paymentType',
            field=models.CharField(db_column='payment_type', default='RH', max_length=2),
        ),
    ]
