# Generated by Django 4.2.16 on 2025-02-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0005_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='registerState',
            field=models.CharField(db_column='register_state', default='P', max_length=1),
        ),
    ]
