# Generated by Django 4.2.16 on 2025-03-25 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0002_alter_userceprunsarolerelation_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0007_remove_course_coordinator_and_more'),
        ('processes', '0007_alter_process_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProcessUserCerprunsaRelation',
            new_name='ProcessUserCeprunsaRelation',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='registerBy',
        ),
        migrations.AddField(
            model_name='observation',
            name='idRegisterBy',
            field=models.ForeignKey(db_column='id_register_by', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='processuserceprunsarelation',
            table='process_user_ceprunsa_relations',
        ),
    ]
