# Generated by Django 4.2.16 on 2025-04-10 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processes', '0008_rename_processusercerprunsarelation_processuserceprunsarelation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='idLastEditedBy',
            field=models.ForeignKey(blank=True, db_column='id_last_edited_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='observation',
            name='lastEditDate',
            field=models.DateField(blank=True, db_column='last_edit_date', null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='idRegisterBy',
            field=models.ForeignKey(db_column='id_register_by', on_delete=django.db.models.deletion.CASCADE, related_name='register_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='observation',
            name='registerState',
            field=models.CharField(db_column='register_state', default='N', max_length=1),
        ),
    ]
