# Generated by Django 4.2.16 on 2024-12-22 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_courseteacherrelation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseteacherrelation',
            name='registerState',
        ),
    ]
