# Generated by Django 4.2.16 on 2025-01-26 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0005_remove_courseteacherrelation_registerstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coordinator',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='subCoordinator',
            field=models.OneToOneField(blank=True, db_column='sub_coordinator', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subCoordinator', to=settings.AUTH_USER_MODEL),
        ),
    ]
