# Generated by Django 4.2.16 on 2025-03-25 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0006_alter_course_coordinator_alter_course_subcoordinator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='coordinator',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subCoordinator',
        ),
        migrations.RemoveField(
            model_name='courseteacherrelation',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseteacherrelation',
            name='teacher',
        ),
        migrations.AddField(
            model_name='course',
            name='idCoordinator',
            field=models.OneToOneField(blank=True, db_column='id_coordinator', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idCoordinator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='idSubCoordinator',
            field=models.OneToOneField(blank=True, db_column='id_sub_coordinator', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idSubCoordinator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseteacherrelation',
            name='idCourse',
            field=models.ForeignKey(db_column='id_course', default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseteacherrelation',
            name='idTeacher',
            field=models.ForeignKey(db_column='id_teacher', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='courseteacherrelation',
            table='course_teacher_relations',
        ),
    ]
