# Generated by Django 4.2.16 on 2024-11-07 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCeprunsaPersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(db_column='first_names', max_length=100)),
                ('lastNames', models.CharField(db_column='last_names', max_length=100)),
                ('phone', models.CharField(db_column='main_phone', max_length=9)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('identityDocument', models.CharField(db_column='identity_document', max_length=8)),
                ('secondPhone', models.CharField(blank=True, db_column='second_phone', max_length=9, null=True)),
                ('personalEmail', models.EmailField(blank=True, db_column='personal_email', max_length=100, null=True)),
                ('cv', models.FileField(blank=True, db_column='cv', null=True, upload_to='cv/')),
                ('academicDegree', models.CharField(db_column='academic_degree', max_length=100)),
                ('career', models.CharField(max_length=100)),
                ('idUserCeprunsa', models.OneToOneField(db_column='id_user_ceprunsa', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'personal_information',
            },
        ),
        migrations.CreateModel(
            name='UserCeprunsaPaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universityRelationship', models.CharField(db_column='university_relationship', max_length=1)),
                ('ruc', models.CharField(blank=True, max_length=11, null=True)),
                ('bankEntity', models.CharField(db_column='bank_entity', max_length=100)),
                ('bankAccount', models.CharField(db_column='bank_account', max_length=20)),
                ('cci', models.CharField(blank=True, max_length=20, null=True)),
                ('suspensionCuarta', models.BooleanField(db_column='suspension_cuarta', default=False)),
                ('idUserCeprunsa', models.OneToOneField(db_column='id_user_ceprunsa', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_information',
            },
        ),
    ]
