# Generated by Django 4.2.16 on 2024-11-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userceprunsapaymentinfo',
            name='suspensionCuarta',
        ),
        migrations.AddField(
            model_name='userceprunsapaymentinfo',
            name='hasFourthSuspension',
            field=models.BooleanField(db_column='has_fourth_suspension', default=False),
        ),
        migrations.AddField(
            model_name='userceprunsapersonalinfo',
            name='birthDate',
            field=models.DateField(blank=True, db_column='birth_date', null=True),
        ),
        migrations.AddField(
            model_name='userceprunsapersonalinfo',
            name='documentType',
            field=models.CharField(db_column='document_type', default='DNI', max_length=3),
        ),
        migrations.AlterField(
            model_name='userceprunsapersonalinfo',
            name='academicDegree',
            field=models.CharField(blank=True, db_column='academic_degree', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userceprunsapersonalinfo',
            name='career',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userceprunsapersonalinfo',
            name='identityDocument',
            field=models.CharField(db_column='identity_document', max_length=12),
        ),
    ]
