# Generated by Django 4.2.16 on 2025-02-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0002_remove_userceprunsapaymentinfo_suspensioncuarta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userceprunsapaymentinfo',
            name='bankAccount',
            field=models.CharField(blank=True, db_column='bank_account', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userceprunsapaymentinfo',
            name='bankEntity',
            field=models.CharField(blank=True, db_column='bank_entity', max_length=100, null=True),
        ),
    ]
