# Generated by Django 4.2.16 on 2025-02-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0003_alter_userceprunsapaymentinfo_bankaccount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userceprunsapersonalinfo',
            name='phone',
            field=models.CharField(db_column='main_phone', max_length=15),
        ),
        migrations.AlterField(
            model_name='userceprunsapersonalinfo',
            name='secondPhone',
            field=models.CharField(blank=True, db_column='second_phone', max_length=15, null=True),
        ),
    ]
