# Generated by Django 4.2.16 on 2025-03-25 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0004_alter_userceprunsapersonalinfo_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userceprunsapersonalinfo',
            name='academicDegree',
            field=models.TextField(blank=True, db_column='academic_degree', null=True),
        ),
        migrations.AlterModelTable(
            name='userceprunsapaymentinfo',
            table='payment_informations',
        ),
        migrations.AlterModelTable(
            name='userceprunsapersonalinfo',
            table='personal_informations',
        ),
    ]
