# Generated by Django 4.2.16 on 2025-03-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0005_alter_userceprunsapersonalinfo_academicdegree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userceprunsapersonalinfo',
            name='academicDegree',
            field=models.CharField(blank=True, db_column='academic_degree', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userceprunsapersonalinfo',
            name='career',
            field=models.TextField(blank=True, null=True),
        ),
    ]
