# Generated by Django 4.2.16 on 2024-11-09 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCeprunsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('joinDate', models.DateTimeField(auto_now_add=True, db_column='join_date')),
                ('registerState', models.CharField(db_column='register_state', default='A', max_length=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users_ceprunsa',
            },
        ),
        migrations.CreateModel(
            name='RoleCeprunsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('registerState', models.CharField(db_column='register_state', default='A', max_length=1)),
            ],
            options={
                'db_table': 'roles_ceprunsa',
            },
        ),
        migrations.CreateModel(
            name='UserCeprunsaRoleRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerState', models.CharField(db_column='register_state', default='A', max_length=1)),
                ('idRole', models.ForeignKey(db_column='id_role_ceprunsa', on_delete=django.db.models.deletion.CASCADE, to='userAuth.roleceprunsa')),
                ('idUser', models.ForeignKey(db_column='id_user_ceprunsa', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_ceprunsa_roles_relation',
            },
        ),
    ]
