# Generated by Django 4.2.16 on 2025-03-25 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userceprunsarolerelation',
            table='user_ceprunsa_roles_relations',
        ),
    ]
